#version 450 core
layout(local_size_x =   5, local_size_y =   5, local_size_z =   5) in;
layout (binding = 0)                    uniform sampler2D velocityIn;
layout (binding = 1, rgba32f) writeonly uniform image2D   velocityOut;
layout (binding = 2)                    uniform sampler2D boundaryBitmap;
layout (binding = 3)                    uniform sampler3D bndQuantityIn;
layout (binding = 4, rgba32f) writeonly uniform image3D   bndQuantityOut;


uniform float ku_dt;
uniform float ku_viscosity;
uniform ivec2 ku_simdims;
uniform vec2  ku_simUnitCoord;
uniform int   ku_normal;
vec2 k_unitCoord  = vec2(1) / vec2(ku_simdims);
vec2 k_simdxdysq  = (ku_simUnitCoord * ku_simUnitCoord);
vec2 k_simrdxdysq = 1.0f / k_simdxdysq;


bool isBoundaryUpdated(ivec2 coords) 
{
    int _flat = coords.y + coords.x * ku_simdims.x;
    if(_flat < 0 || _flat > ku_simdims.x * ku_simdims.y - 1) {
        return true;
    }
    return texelFetch(boundaryBitmap, coords, 0).x > 0.0f;
}


void mainBoundary()
{
    vec4  result = vec4(0);
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 neighbouridx[4] = ivec2[4](
        texelCoord + ivec2(1, 0), /* right */
        texelCoord - ivec2(1, 0), /* left  */
        texelCoord + ivec2(0, 1), /* up    */
        texelCoord - ivec2(0, 1)  /* down  */
    );
    float boundarybits[4] = float[4](
        float( isBoundaryUpdated(neighbouridx[0]) ),
        float( isBoundaryUpdated(neighbouridx[1]) ),
        float( isBoundaryUpdated(neighbouridx[2]) ),
        float( isBoundaryUpdated(neighbouridx[3]) ) 
    );
    ivec3 bndQuantityIdx[4] = ivec3[4](
        ivec3(neighbouridx[0], 1),
        ivec3(neighbouridx[0], 0),
        ivec3(neighbouridx[0], 3),
        ivec3(neighbouridx[0], 2)
    );
    vec2 neighbourValues[4] = vec2[4](
        texelFetch(velocityIn, neighbouridx[0], 0).xy,
        texelFetch(velocityIn, neighbouridx[0], 1).xy,
        texelFetch(velocityIn, neighbouridx[0], 2).xy,
        texelFetch(velocityIn, neighbouridx[0], 3).xy
    );
    vec4 bndQuantityNeighbours[4] = vec4[4](
        texelFetch(bndQuantityIn, bndQuantityIdx[0], 0),
        texelFetch(bndQuantityIn, bndQuantityIdx[1], 0),
        texelFetch(bndQuantityIn, bndQuantityIdx[2], 0),
        texelFetch(bndQuantityIn, bndQuantityIdx[3], 0)
    );


    if(isBoundaryUpdated(texelCoord)) {
        vec2 ifBoundarySetZeroElseSetNeighbourValue;
        for(int i = 0; i < 4; ++i) 
        {
            ifBoundarySetZeroElseSetNeighbourValue = mix(
                neighbourValues[i],
                vec2(0),
                boundarybits[i]
            );
            result = bndQuantityNeighbours[i];
            result.xy = ifBoundarySetZeroElseSetNeighbourValue;
            imageStore(bndQuantityOut, ivec3(texelCoord, i), result);
        }
    } else {
        vec2 ifBoundarySetBndQuantityElseSetNeighbourValue;

        for(int i = 0; i < 4; ++i) {
            ifBoundarySetBndQuantityElseSetNeighbourValue = mix(
                neighbourValues[i],
                bndQuantityNeighbours[i].xy,
                boundarybits[i]
            );
            neighbourValues[i] = ifBoundarySetBndQuantityElseSetNeighbourValue;
        }
        vec2 sigmaX = k_simrdxdysq.x * (neighbourValues[0] + neighbourValues[1]);
        vec2 sigmaY = k_simrdxdysq.y * (neighbourValues[2] + neighbourValues[3]);
        float alpha = ku_viscosity * ku_dt;
        float lambda = 1 - alpha * 2 * (k_simrdxdysq.x + k_simrdxdysq.y);

        result.xy = lambda * texelFetch(velocityIn, texelCoord, 0).xy + alpha * (sigmaX + sigmaY);
        imageStore(velocityOut, texelCoord, result);
    }


    return;
}


bvec4 isBoundary(ivec2 coords) {
    /* if .xy components are 1, the pixel is on the bottom left  */
    /* if .zw components are 1, the pixel is on the top    right */
    /* we can add/subtract them to get the neighbouring pixel (not on the boundary) */
    return bvec4(
        coords.x <= 0, 
        coords.y <= 0,
        coords.x >= (ku_simdims.x - 1),
        coords.y >= (ku_simdims.y - 1)
    );
}


bvec4 isBoundary2(ivec2 coords) {
    return bvec4(
        texelFetch(boundaryBitmap, coords, 0).x > 0.0f,
        texelFetch(boundaryBitmap, coords, 0).x > 0.0f,
        texelFetch(boundaryBitmap, coords, 0).x > 0.0f,
        texelFetch(boundaryBitmap, coords, 0).x > 0.0f
    );
}


vec2 newVelocity(
    in sampler2D x,
    in ivec2     ij,
    in vec2      xij
) {
    vec2 neighbours[4] = vec2[4](
        texelFetch(x, ij + ivec2(1, 0), 0).xy,
        texelFetch(x, ij - ivec2(1, 0), 0).xy,
        texelFetch(x, ij + ivec2(0, 1), 0).xy,
        texelFetch(x, ij - ivec2(0, 1), 0).xy
    );
    float _alpha = ku_viscosity * ku_dt * (k_simrdxdysq.x * k_simrdxdysq.y);
    vec2 sigmai = neighbours[0] + neighbours[1];
    vec2 sigmaj = neighbours[2] + neighbours[3];
    float _uij  = (1.0f / _alpha) - 2.0f * (k_simdxdysq.y + k_simdxdysq.x);

    sigmai *= k_simdxdysq.y;
    sigmaj *= k_simdxdysq.x;
    return  _alpha * ( sigmai + sigmaj + _uij * xij );
}


void mainNoBoundary()
{
    ivec2 texelCoord, texelToFetch;
    bvec4 boundaryBits;
    bool  onTheBoundary;
    vec2  result, IfBoundaryThenResultElseValueIJ, IfBoundaryIgnoreElseResult; 
    float IfBoundaryNegateElseKeepSame;


    texelCoord    = ivec2(gl_GlobalInvocationID.xy);
    boundaryBits  = isBoundary(texelCoord);
    onTheBoundary = any(boundaryBits);
    texelToFetch  = texelCoord + ivec2(boundaryBits.xy) - ivec2(boundaryBits.zw);
    
    IfBoundaryNegateElseKeepSame    = mix(1.0f, -1.0f, float(onTheBoundary));
    IfBoundaryThenResultElseValueIJ = IfBoundaryNegateElseKeepSame * texelFetch(velocityIn, texelToFetch, 0).xy;
    IfBoundaryIgnoreElseResult      = newVelocity(velocityIn, texelCoord, IfBoundaryThenResultElseValueIJ);
    result = mix(
        IfBoundaryIgnoreElseResult,
        IfBoundaryThenResultElseValueIJ,
        vec2(float(onTheBoundary))
    );

    imageStore(velocityOut, texelCoord, vec4(result, 0.0f, 0.0f));
    return;
}




void main()
{
    if(bool(ku_normal))
    {
        mainNoBoundary();
    } else {
        mainBoundary();
    }
}