#version 450 core
layout(local_size_x =   5, local_size_y =   5, local_size_z =   5) in;
layout (binding = 0)                    uniform sampler2D velocityIn;
layout (binding = 1, rgba32f) writeonly uniform image2D   velocityOut;
layout (binding = 2)                    uniform sampler2D boundaryBitmap;
layout (binding = 3)                    uniform sampler3D bndQuantityIn;
layout (binding = 4, rgba32f) writeonly uniform image3D   bndQuantityOut;


uniform float ku_dt;
uniform float ku_viscosity;
uniform ivec2 ku_simdims;
uniform vec2  ku_simUnitCoord;
vec2 k_unitCoord  = vec2(1) / vec2(ku_simdims);
vec2 k_simdxdysq  = (ku_simUnitCoord * ku_simUnitCoord);
vec2 k_simrdxdysq = 1.0f / k_simdxdysq;


bool isBoundary(ivec2 coords) 
{
    int _flat = coords.y + coords.x * ku_simdims.x;
    if(_flat < 0 || _flat > ku_simdims.x * ku_simdims.y - 1) {
        return true;
    }
    return texelFetch(boundaryBitmap, coords, 0).x > 0.0f;
}


void main()
{
    vec4  result = vec4(0);
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 neighbouridx[4] = ivec2[4](
        texelCoord + ivec2(1, 0), /* right */
        texelCoord - ivec2(1, 0), /* left  */
        texelCoord + ivec2(0, 1), /* up    */
        texelCoord - ivec2(0, 1)  /* down  */
    );
    float boundarybits[4] = float[4](
        float( isBoundary(neighbouridx[0]) ),
        float( isBoundary(neighbouridx[1]) ),
        float( isBoundary(neighbouridx[2]) ),
        float( isBoundary(neighbouridx[3]) ) 
    );
    ivec3 bndQuantityIdx[4] = ivec3[4](
        ivec3(neighbouridx[0], 1),
        ivec3(neighbouridx[0], 0),
        ivec3(neighbouridx[0], 3),
        ivec3(neighbouridx[0], 2)
    );
    vec2 neighbourValues[4] = vec2[4](
        texelFetch(velocityIn, neighbouridx[0], 0).xy,
        texelFetch(velocityIn, neighbouridx[0], 1).xy,
        texelFetch(velocityIn, neighbouridx[0], 2).xy,
        texelFetch(velocityIn, neighbouridx[0], 3).xy
    );
    vec4 bndQuantityNeighbours[4] = vec4[4](
        texelFetch(bndQuantityIn, bndQuantityIdx[0], 0),
        texelFetch(bndQuantityIn, bndQuantityIdx[1], 0),
        texelFetch(bndQuantityIn, bndQuantityIdx[2], 0),
        texelFetch(bndQuantityIn, bndQuantityIdx[3], 0)
    );


    if(isBoundary(texelCoord)) {
        vec2 ifBoundarySetZeroElseSetNeighbourValue;
        for(int i = 0; i < 4; ++i) 
        {
            ifBoundarySetZeroElseSetNeighbourValue = mix(
                neighbourValues[i],
                vec2(0),
                boundarybits[i]
            );
            result = bndQuantityNeighbours[i];
            result.xy = ifBoundarySetZeroElseSetNeighbourValue;
            imageStore(bndQuantityOut, ivec3(texelCoord, i), result);
        }
    } else {
        vec2 ifBoundarySetBndQuantityElseSetNeighbourValue;

        for(int i = 0; i < 4; ++i) {
            ifBoundarySetBndQuantityElseSetNeighbourValue = mix(
                neighbourValues[i],
                bndQuantityNeighbours[i].xy,
                boundarybits[i]
            );
            neighbourValues[i] = ifBoundarySetBndQuantityElseSetNeighbourValue;
        }
        vec2 sigmaX = k_simrdxdysq.x * (neighbourValues[0] + neighbourValues[1]);
        vec2 sigmaY = k_simrdxdysq.y * (neighbourValues[2] + neighbourValues[3]);
        float alpha = ku_viscosity * ku_dt;
        float lambda = 1 - alpha * 2 * (k_simrdxdysq.x + k_simrdxdysq.y);

        result.xy = lambda * texelFetch(velocityIn, texelCoord, 0).xy + alpha * (sigmaX + sigmaY);
        imageStore(velocityOut, texelCoord, result);
    }


    return;
}