#version 450 core
layout(local_size_x =   5, local_size_y =   5, local_size_z =   5) in;
layout (binding = 0)                    uniform sampler2D initialField;
layout (binding = 1, rgba32f) writeonly uniform image2D   outputField;
layout (binding = 2)                    uniform sampler2D boundaryBitmap;
layout (binding = 3)                    uniform sampler3D initialBndQuantity;
layout (binding = 4, rgba32f) writeonly uniform image3D   outputBndQuantity;


bool isBoundary(ivec2 coords);


/* 
    Single iteration of a jacobi solver
*/
vec2 laplacian(
    in sampler2D x,
    in ivec2 ij,
    in vec2  xij
);
vec2 newVelocity(
    in sampler2D x,
    in ivec2     ij,
    in vec2      xij
);


uniform float ku_dt;
uniform float ku_viscosity;
uniform ivec2 ku_simdims;
uniform vec2  ku_simUnitCoord;
vec2 k_unitCoord  = vec2(1) / vec2(ku_simdims);
vec2 k_simrdxdysq = 1.0f / (ku_simUnitCoord * ku_simUnitCoord);
vec2 k_simdxdysq  = (ku_simUnitCoord * ku_simUnitCoord);


void main()
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    if(isBoundary(texelCoord)) {
        bool boundarybits[4] = bool[4](
            isBoundary(texelCoord + ivec2(1, 0)), /* right */ 
            isBoundary(texelCoord - ivec2(1, 0)), /* left  */ 
            isBoundary(texelCoord + ivec2(0, 1)), /* up    */ 
            isBoundary(texelCoord - ivec2(0, 1))  /* down  */ 
        );
        vec2 boundaryNeighbours[4] = vec2[4](
            texelFetch(initialField, texelCoord + ivec2(1, 0), 0).xy,
            texelFetch(initialField, texelCoord - ivec2(1, 0), 0).xy,
            texelFetch(initialField, texelCoord + ivec2(0, 1), 0).xy,
            texelFetch(initialField, texelCoord - ivec2(0, 1), 0).xy
        );
        for(int i = 0; i < 4; ++i) {
            imageStore(outputBndQuantity, 
                ivec3(texelCoord, i), 
                vec4(
                    mix(-1.0f, 0.0f, float(boundarybits[i])) * boundaryNeighbours[i], 
                    0, 
                    0
                )
            );
        }
        return;
    }


    vec2 result = newVelocity(
        initialField, 
        texelCoord, 
        texelFetch(initialField, texelCoord, 0).xy
    );
    imageStore(outputField, texelCoord, vec4(result, 0.0f, 0.0f));
    return;
}


bool isBoundary(ivec2 coords) {
    int _flat = coords.y + coords.x * ku_simdims.x;
    if(_flat < 0 || _flat > ku_simdims.x * ku_simdims.y - 1) {
        return true;
    }
    return texelFetch(boundaryBitmap, coords, 0).x > 0.0f;
}


vec2 laplacian(
    in sampler2D x,
    in ivec2 ij,
    in vec2 xij
) {
    vec2 result = vec2(0.0f);
    bvec4 boundarybits = bvec4(
        isBoundary(ij + ivec2(1, 0)), /* right */ 
        isBoundary(ij - ivec2(1, 0)), /* left  */ 
        isBoundary(ij + ivec2(0, 1)), /* up    */ 
        isBoundary(ij - ivec2(0, 1))  /* down  */ 
    );
    vec2 neighbourValues[4] = vec2[4](
        texelFetch(initialField, ij + ivec2(1, 0), 0).xy,
        texelFetch(initialField, ij - ivec2(1, 0), 0).xy,
        texelFetch(initialField, ij + ivec2(0, 1), 0).xy,
        texelFetch(initialField, ij - ivec2(0, 1), 0).xy
    );
    vec2 boundaryValues[4] = vec2[4](
        texelFetch(initialBndQuantity, ivec3( ij + ivec2(1, 0), 1 ), 0).xy,
        texelFetch(initialBndQuantity, ivec3( ij - ivec2(1, 0), 0 ), 0).xy,
        texelFetch(initialBndQuantity, ivec3( ij + ivec2(0, 1), 3 ), 0).xy,
        texelFetch(initialBndQuantity, ivec3( ij - ivec2(0, 1), 2 ), 0).xy
    );
    neighbourValues[0] = mix( neighbourValues[0], boundaryValues[0], float(boundarybits.x) );
    neighbourValues[1] = mix( neighbourValues[1], boundaryValues[1], float(boundarybits.y) );
    neighbourValues[2] = mix( neighbourValues[2], boundaryValues[2], float(boundarybits.z) );
    neighbourValues[3] = mix( neighbourValues[3], boundaryValues[3], float(boundarybits.w) );


    result += (neighbourValues[0] + neighbourValues[1] - 2.0f * xij) * k_simrdxdysq.y;
    result += (neighbourValues[2] + neighbourValues[3] - 2.0f * xij) * k_simrdxdysq.x;
    return result;
}


vec2 newVelocity(
    in sampler2D x,
    in ivec2     ij,
    in vec2      xij
) {
    bvec4 boundarybits = bvec4(
        isBoundary(ij + ivec2(1, 0)), /* right */ 
        isBoundary(ij - ivec2(1, 0)), /* left  */ 
        isBoundary(ij + ivec2(0, 1)), /* up    */ 
        isBoundary(ij - ivec2(0, 1))  /* down  */ 
    );
    vec2 neighbourValues[4] = vec2[4](
        texelFetch(initialField, ij + ivec2(1, 0), 0).xy,
        texelFetch(initialField, ij - ivec2(1, 0), 0).xy,
        texelFetch(initialField, ij + ivec2(0, 1), 0).xy,
        texelFetch(initialField, ij - ivec2(0, 1), 0).xy
    );
    vec2 boundaryValues[4] = vec2[4](
        texelFetch(initialBndQuantity, ivec3( ij + ivec2(1, 0), 1 ), 0).xy,
        texelFetch(initialBndQuantity, ivec3( ij - ivec2(1, 0), 0 ), 0).xy,
        texelFetch(initialBndQuantity, ivec3( ij + ivec2(0, 1), 3 ), 0).xy,
        texelFetch(initialBndQuantity, ivec3( ij - ivec2(0, 1), 2 ), 0).xy
    );
    neighbourValues[0] = mix( neighbourValues[0], boundaryValues[0], float(boundarybits.x) );
    neighbourValues[1] = mix( neighbourValues[1], boundaryValues[1], float(boundarybits.y) );
    neighbourValues[2] = mix( neighbourValues[2], boundaryValues[2], float(boundarybits.z) );
    neighbourValues[3] = mix( neighbourValues[3], boundaryValues[3], float(boundarybits.w) );


    float _alpha = ku_viscosity * ku_dt * (k_simrdxdysq.x * k_simrdxdysq.y);
    vec2 sigmai = neighbourValues[0] + neighbourValues[1];
    vec2 sigmaj = neighbourValues[2] + neighbourValues[3];
    float _uij  = (1.0f / _alpha) - 2.0f * (k_simdxdysq.y + k_simdxdysq.x);

    sigmai *= k_simdxdysq.y;
    sigmaj *= k_simdxdysq.x;
    return  _alpha * ( sigmai + sigmaj + _uij * xij );
}